server:
  port: 8081


     
spring:
 cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
      - id: rs-1
        uri: http://localhost:8080/
        predicates:
        - Path= /rs1/**
        filters:
        - StripPrefix=1
     

 application:
  name: spring-gateway
 zipkin:
    base-url: http://localhost:9411/
 sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    org.springframework: INFO
#  config: logback-spring.xml

